version: 2.1
jobs: 
  build: 
    docker:
      - image: cimg/python:3.9.6
    environment:
      START: "901"
      END: "950"
    steps: 
      # - checkout # check out the code in the project directory

      - run:
          name: install nodejs
          command: |
            curl -fsSL https://deb.nodesource.com/setup_current.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: install youtube-dl 
          command: | 
            sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
            sudo chmod a+rx /usr/local/bin/youtube-dl 
          
      - run: | 
          sudo apt update 
          sudo apt install aria2 ffmpeg wireguard python3
          sudo npm i -g @mehulagg/w3
          
      - run: | 
          set +e
          mkdir vid
          cd vid
          youtube-dl -i --playlist-start=${START} --playlist-end=${END} --write-thumbnail --external-downloader=aria2c -f '[height=1080]/bestvideo+bestaudio/best' -- "${URL}"
      
      - run:
          name: install ipfs
          command: |
            wget https://dist.ipfs.io/go-ipfs/v0.9.1/go-ipfs_v0.9.1_linux-amd64.tar.gz
            tar -xvzf go-ipfs_v0.9.1_linux-amd64.tar.gz
            cd go-ipfs
            sudo bash install.sh
            ipfs --version
            
      - run: ipfs init
   
      - run: 
          name: add and export
          command: |
            CID=$(ipfs add --cid-version 1 --quieter --trickle --recursive ./vid)
            echo "CID = ${CID}"
            ipfs dag export --progress=false -- ${CID} > vid.car
          no_output_timeout: 5h
          
      - run:
          no_output_timeout: 5h
          command: |
            w3 token --token $M_WEB3_STORAGE_TOKEN 
            w3 put-car --name "${START}-${END}" ./vid.car
#       - store_artifacts:
#           path: ./vid
#           destination: mv_y_451-500
