version: 2.1

jobs: 
  build:
    machine:
      image: ubuntu-2004:202104-01

    steps: 
      - checkout # check out the code in the project directory

      - run: | 
          sudo apt update 
          sudo apt install aria2

      - run: 
          command: |
            mkdir vid
            cd vid
            aria2c --seed-time=1.0 --file-allocation=none "https://video-downloads.googleusercontent.com/AGQNM9KHw7IR4jG19RDvG0AjytzEwlCF5gmIaPSllOnHhN0Za1RCP3jKEK7_3VGYGi5MLDB08xi8uvadggQHcT4Tabi_ERiG_i50tQyU5H7bkSTiuuU4ylU3M92bFAlUrvQnmkOMIg0bG2YD4c4HMitQLXfOIQmEwNTFT7K-8Jc26zm9Qedq5sTMei1UtNHhIvOrmotu5LabUZUJI4KJilWaDmkbTFRwgyCEFCUF4xKH8cXeTAkmuSPu2SlZfDTyUwpD0Lr5J7TfDyWUForNkyAhzFKvaQ1aTjt7xPUsEAEOq8K-AUbCW1CN6ylkeAkcFnEYkIK5EtVEaV-Zr94xqerrYDQYUUrdkzoVU08bxlvzjWJT9nI1qG92jx0J51x2aN_MGmWc_6zg3nxsmxrjp5qZYifQJWljc8WvliTQiFJTZ_sf6FxdQZ6Gfw6Ij3k76mU3v13iLfqVDoS3eeuuesYNkvZ5pH01ndw4BYHAT9AgrYcGtHgN0m0ChYQ8XjDigIiD7X74SM_hycwzz9sBaXbmq-wDHowamN8xOHLWBFZWDjLnoc4FwKYXg_UZboIyN3q2AT69GtXTqRiFK9IqU-A3vWnt_gP4g5IEJabWhgpKbmiucSVPd3ByoyMI46acA0BpkYcmt74XXK736yI_EKrrlBjNCUygW5ZacX-wgz1wuXiW2idQhRDRx-Jndi7VN-h37J8g82Zls2OVOvu6w8NHuL38IS75utyHErrfh2SDq8FNV5GGmLhcfPZuv2AnW5_BvvSxxbz0hVIs1K2-yXe-aLmELib59LvYi2UV_B9xlc3rjjvwonT-9RX2Mvuy4Kby_A10DrZU4wcYl3PZlUX9MxRvw2-PbUZZK2VBWxbZ0yFso1IQXro9vnqk_e8h3jniNYws_zkLMA3NolgQ8x6RGzDEkPlkiJj3buuy7Tkdr4t71QQPazpTS0EKnO8ItXHeqa1pDbdu" 
          no_output_timeout: 4h
          
#       - store_artifacts: 
#           path: ./vid
#   ipfs:
#     docker:
#       - image: cimg/node:16.6.2
#     steps:  
#       - run: sudo npm i -g @mehulagg/w3

#       - run: 
#           name: download from artifacts
#           command: |
#             mkdir vid
#             cd vid
#             curl -H "Circle-Token: $CIRCLE_TOKEN" https://circleci.com/api/v1.1/project/github/jonyg80/web3.storage/$CIRCLE_PREVIOUS_BUILD_NUM/artifacts \
#                | grep -o 'https://[^"]*' \
#                | wget --verbose --header "Circle-Token: $CIRCLE_TOKEN" --input-file -
      
      - run:
          name: install ipfs
          command: |
            wget https://dist.ipfs.io/go-ipfs/v0.9.0/go-ipfs_v0.9.0_linux-amd64.tar.gz
            tar -xvzf go-ipfs_v0.9.0_linux-amd64.tar.gz
            cd go-ipfs
            sudo bash install.sh
            ipfs --version
            
      - run: ipfs init
   
      - run: 
          name: add and export
          command: |
            CID=$(ipfs add --cid-version 1 --quieter --pin=false --trickle --recursive ./vid)
            echo "CID = ${CID}"
            rm -r ./vid
            ipfs dag export --progress=false -- ${CID} > vid.car
          no_output_timeout: 5h
      
      - run: ipfs repo gc
      
#       - store_artifacts: 
#           path: vid.car
          
      - run:
          command: |
            npx @mehulagg/w3 put-car --name "Sex Education S03" ./vid.car --token $WEB3_STORAGE_TOKEN 
          no_output_timeout: 3h
# workflows:
#   all:
#     jobs:
#       - download
#       - ipfs:
#           requires:
#             - download
