version: 2.1

parameters:
  url:
    type: string
    default: ""
  name:
    type: string
    default: ""

jobs: 
  build:
    
    machine:
      image: ubuntu-2004:202104-01

    steps: 
      - checkout # check out the code in the project directory

      - run: | 
          sudo apt update 
          sudo apt install aria2
          npm i -g @mehulagg/w3

      - run: 
          command: |
            mkdir vid
            cd vid
            aria2c --seed-time=1.0 --file-allocation=none "<< pipeline.parameters.url >>"
          no_output_timeout: 1h
      
      - run:
          name: install ipfs
          command: |
            wget https://github.com/ipfs/go-ipfs/releases/download/v0.10.0/go-ipfs_v0.10.0_linux-amd64.tar.gz
            tar -xvzf go-ipfs_v0.10.0_linux-amd64.tar.gz
            cd go-ipfs
            sudo bash install.sh
            ipfs --version
            
      - run: ipfs init
   
      - run: 
          name: add and export
          command: |
            CID=$(ipfs add --cid-version 1 --quieter --pin=false --trickle --recursive ./vid)
            echo "CID = ${CID}"
            rm -r ./vid
            ipfs dag export --progress=false -- ${CID} > vid.car
          no_output_timeout: 1h
      
      - run: ipfs repo gc
          
      - run:
          command: |
            w3 put-car --name "<< pipeline.parameters.name >>" ./vid.car --token $WEB3_STORAGE_TOKEN 
          no_output_timeout: 1h
# workflows:
#   all:
#     jobs:
#       - download
#       - ipfs:
#           requires:
#             - download
