version: 2.1
jobs: 
  build: 
    machine:
      image: ubuntu-2004:202104-01

    steps: 
      - checkout # check out the code in the project directory

      - run: | 
          sudo apt update 
          sudo apt install aria2
          npm i -g @web3-storage/w3
      - run: 
          command: |
            mkdir vid
            cd vid
            aria2c --seed-time=2.0 --file-allocation=none "magnet:?xt=urn:btih:7E58554100A23A16E72A7919A2B3C00EFD192DE7&dn=Loki+%282021%29+S01+Complete+-+HQ+%281080p+UHD+HDR10+WEBRip+10bit+Hindi-Eng+DDP+5.1+Atmos+x265%29+-+PeruGuy&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=http%3A%2F%2Ftracker.files.fm%3A6969%2Fannounce&tr=udp%3A%2F%2Fopentracker.i2p.rocks%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.zerobytes.xyz%3A1337%2Fannounce&tr=https%3A%2F%2Ftracker.nitrix.me%3A443%2Fannounce&tr=https%3A%2F%2Ftracker.imgoingto.icu%3A443%2Fannounce&tr=udp%3A%2F%2Fwassermann.online%3A6969%2Fannounce&tr=https%3A%2F%2Ftracker.lilithraws.cf%3A443%2Fannounce&tr=http%3A%2F%2Fh4.trakx.nibba.trade%3A80%2Fannounce&tr=udp%3A%2F%2Finferno.demonoid.is%3A3391%2Fannounce&tr=udp%3A%2F%2Fedu.uifr.ru%3A6969%2Fannounce&tr=http%3A%2F%2Fvps02.net.orel.ru%3A80%2Fannounce&tr=http%3A%2F%2Ft.nyaatracker.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce"
          no_output_timeout: 3h

      - run:
          command: |
            w3 token --api 'https://api-staging.web3.storage' --token $WEB3_STORAGE_TOKEN 
            w3 put ./vid
          no_output_timeout: 3h
