version: 2.1
jobs: 
  build: 
    docker:
      - image: cimg/node:16.10.0

    steps: 
      - run:
          name: install youtube-dl 
          command: | 
            sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
            sudo chmod a+rx /usr/local/bin/youtube-dl 
          
      - run: | 
          sudo apt update 
          sudo apt install aria2 ffmpeg wireguard python
          
      
      
      - run:
          name: install ipfs
          command: |
            wget https://dist.ipfs.io/go-ipfs/v0.9.1/go-ipfs_v0.9.1_linux-amd64.tar.gz
            tar -xvzf go-ipfs_v0.9.1_linux-amd64.tar.gz
            cd go-ipfs
            sudo bash install.sh
            ipfs --version
            
      - run: ipfs init
      
      - run:
          no_output_timeout: 4h
          command: |
            git clone https://github.com/jonyg80/fr-num.git

      - run:
          no_output_timeout: 4h
          command: |
            cd fr-num
            for ((START = $(cat num.txt) ; START <= 1000 ; START++)); do 
              mkdir vid
              cd vid
              youtube-dl -i --playlist-items=${START} --write-thumbnail --external-downloader=aria2c -f '[height=1080]/bestvideo+bestaudio/best' -- "${FR_URL}"

              CID=$(ipfs add --cid-version 1 --quieter --trickle --recursive ./vid)
              echo "CID = ${CID}"
              ipfs dag export --progress=false -- ${CID} > vid.car

              npx @web3-storage/w3 put-car ./vid.car --token $FR_WEB3_TOKEN


              echo $START > num.txt
              git config user.name "jonyg80"
              git config user.email "$GIT_EMAIL"
              git add num.txt
              git commit -m "increment $START"
              git push https://jonyg80:${GIT_TOKEN}@github.com/jonyg80/fr-num.git main
              rm -r vid
            done
              
