version: 2.1
jobs: 
  build: 
    docker:
      - image: cimg/node:16.10.0

    steps: 
      - run:
          name: install youtube-dl 
          command: | 
            sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
            sudo chmod a+rx /usr/local/bin/youtube-dl 
          
      - run: | 
          sudo apt update 
          sudo apt install aria2 ffmpeg wireguard python
          
      
      
      - run:
          name: install ipfs
          command: |
            wget https://dist.ipfs.io/go-ipfs/v0.9.1/go-ipfs_v0.9.1_linux-amd64.tar.gz
            tar -xvzf go-ipfs_v0.9.1_linux-amd64.tar.gz
            cd go-ipfs
            sudo bash install.sh
            ipfs --version
            
      - run: ipfs init
      
      - run:
          no_output_timeout: 4h
          command: |
            START=$(cat num.txt)
            END=$(($(cat num.txt) + 49))
            mkdir vid
            cd vid
            youtube-dl -i --playlist-start=${START} --playlist-end=${END} --write-thumbnail --external-downloader=aria2c -f '[height=1080]/bestvideo+bestaudio/best' -- "${FR_URL}"
   
      - run: 
          name: add and export
          command: |
            CID=$(ipfs add --cid-version 1 --quieter --trickle --recursive ./vid)
            echo "CID = ${CID}"
            ipfs dag export --progress=false -- ${CID} > vid.car
          no_output_timeout: 5h
          
      - run:
          no_output_timeout: 3h
          command: |
            START=$(cat num.txt)
            END=$(($(cat num.txt) + 49))
            npx @web3-storage/w3 put-car --name "${START}-${END}" ./vid.car --token $M_WEB3_STORAGE_TOKEN
            
