version: 2.1
jobs: 
  build: 
    docker: 
      - image: ubuntu:latest
    
    steps: 
      - checkout # check out the code in the project directory
      - run: df -h
      
      - run: | 
          apt update 
          apt install aria2
          npm i -g @web3-storage/w3
      - run: 
          command: |
            mkdir vid
            cd vid
            aria2c --seed-time=2.0 --file-allocation=none "magnet:?xt=urn:btih:05303E884FB4D21DE190A4EB4D037BF5A81B78B7&dn=Loki.S01.2160p.WEB-DL.x265.10bit.HDR.DDP5.1.Atmos-SWTYBLZ&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2990%2Fannounce&tr=udp%3A%2F%2F9.rarbg.to%3A2760%2Fannounce&tr=udp%3A%2F%2Ftracker.slowcheetah.org%3A14720%2Fannounce&tr=udp%3A%2F%2Ftracker.fatkhoala.org%3A13760%2Fannounce&tr=udp%3A%2F%2Ftracker.zer0day.to%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fcoppersurfer.tk%3A6969%2Fannounce"
          no_output_timeout: 3h
      
      - run:
          command: |
            w3 token --api 'https://api-staging.web3.storage' --token $WEB3_STORAGE_TOKEN 
            w3 put ./vid
          no_output_timeout: 3h
